trigger:
  - master  # Adjust based on your branch name

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: '1.6.0'

# Step 1: Initialize, Plan, and Apply
- script: |
    terraform init
    terraform plan
    terraform apply -auto-approve
  env:
    TF_VAR_project_key: $(PROJECT_KEY)
    TF_VAR_client_id: $(CLIENT_ID)
    TF_VAR_client_secret: $(CLIENT_SECRET)
  displayName: 'Initialize, Plan, and Apply Terraform'

# Step 2: Manual Approval for Destroy
- task: ManualValidation
  inputs:
    instructions: 'Approve to destroy the resources.'
    onTimeout: 'reject'
  displayName: 'Manual Approval Before Destroy'

# Step 3: Terraform Destroy (Manual Trigger)
- script: |
    terraform destroy -auto-approve
  env:
    TF_VAR_project_key: $(PROJECT_KEY)
    TF_VAR_client_id: $(CLIENT_ID)
    TF_VAR_client_secret: $(CLIENT_SECRET)
  displayName: 'Terraform Destroy'
  condition: succeeded() 
