trigger:
- master  # Adjust based on your branch name

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'

- script: |
    terraform init
    terraform plan
    terraform apply -auto-approve
  env:
    TF_VAR_project_key: $(PROJECT_KEY)
    TF_VAR_client_id: $(CLIENT_ID)
    TF_VAR_client_secret: $(CLIENT_SECRET)
