trigger:
  - master  # Adjust based on your branch name

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: '1.6.0'

# Step 1: Initialize, Plan, and Apply
- script: |
    terraform init
    terraform plan
    terraform apply -auto-approve
  env:
    TF_VAR_project_key: $(PROJECT_KEY)
    TF_VAR_client_id: $(CLIENT_ID)
    TF_VAR_client_secret: $(CLIENT_SECRET)
  displayName: 'Initialize, Plan, and Apply Terraform'

# Step 2: Destroy the resources after creation
- script: |
    terraform destroy 
  env:
    TF_VAR_project_key: $(PROJECT_KEY)
    TF_VAR_client_id: $(CLIENT_ID)
    TF_VAR_client_secret: $(CLIENT_SECRET)
  displayName: 'Destroy Terraform Resources'
  condition: succeeded()  # This ensures destroy happens only if the previous steps succeed

